// front-svelte/src/routes/interview/+page.svelte
<script lang="ts">
    import { page } from '$app/stores';
    import { trpc } from '$lib/trpc';
    import { onMount } from 'svelte';
    import { 
        MessageSquare, 
        Wand2, 
        ChevronDown, 
        ChevronUp, 
        BookOpen, 
        Building2,
        FileText,
        History,
        Upload,
        AlertCircle,
        Loader2
    } from 'lucide-svelte';
    import { fade, slide } from 'svelte/transition';
    
    // State (Using Svelte 5 $state)
    let inputMode = $state<'text' | 'select' | 'file'>('text');
    let writings = $state<any[]>([]);
    let styles = $state<any[]>([]);
    let corporates = $state<any[]>([]);
    
    let selectedWritingId = $state<number | undefined>(undefined);
    let selectedStyleId = $state<number | undefined>(undefined);
    let selectedCorporateId = $state<number | undefined>(undefined);
    let manualText = $state('');
    let questionCount = $state(5);
    
    let generatedQuestions = $state<any[]>([]);
    let isGenerating = $state(false);
    let isExtracting = $state(false);
    let expandedIndex = $state<number | null>(null);
    let error = $state('');

    // Fetch Initial Data
    $effect(() => {
        const client = trpc($page);
        client.writing.getHistory.query().then(res => writings = res);
        client.interviewLearning.listStyles.query().then(res => styles = res);
        client.corporate.list.query().then(res => corporates = res);
    });

    async function handleFileUpload(e: Event) {
        const file = (e.target as HTMLInputElement).files?.[0];
        if (!file) return;

        isExtracting = true;
        error = '';
        
        const formData = new FormData();
        formData.append('file', file);

        try {
            const response = await fetch('/api/analysis/upload/extract', {
                method: 'POST',
                body: formData,
            });

            if (!response.ok) throw new Error('파일 분석에 실패했습니다.');

            const data = await response.json();
            manualText = data.text;
            inputMode = 'text'; // Switch to text to show extracted content
        } catch (e: any) {
            error = e.message;
        } finally {
            isExtracting = false;
        }
    }

    async function handleGenerate() {
        if (inputMode === 'text' && !manualText.trim()) {
            error = '자소서 내용을 입력해주세요.';
            return;
        }
        if (inputMode === 'select' && !selectedWritingId) {
            error = '자소서를 선택해주세요.';
            return;
        }

        isGenerating = true;
        error = '';
        generatedQuestions = [];
        expandedIndex = null;

        try {
            const result = await trpc($page).interview.generateQuestions.mutate({
                writingId: inputMode === 'select' ? selectedWritingId : undefined,
                coverLetterText: inputMode === 'text' ? manualText : undefined,
                interviewStyleId: selectedStyleId,
                corporateId: selectedCorporateId,
                questionCount
            });
            generatedQuestions = result.questions;
        } catch (e: any) {
            console.error(e);
            error = e.message || '질문 생성에 실패했습니다.';
        } finally {
            isGenerating = false;
        }
    }

    function getDifficultyColor(difficulty: string) {
        switch (difficulty?.toLowerCase()) {
            case 'easy': return 'bg-green-100 text-green-700 border-green-200';
            case 'medium': return 'bg-yellow-100 text-yellow-700 border-yellow-200';
            case 'hard': return 'bg-red-100 text-red-700 border-red-200';
            default: return 'bg-gray-100 text-gray-700 border-gray-200';
        }
    }

    function getDifficultyLabel(difficulty: string) {
        switch (difficulty?.toLowerCase()) {
            case 'easy': return '기본';
            case 'medium': return '중급';
            case 'hard': return '심화';
            default: return difficulty || '보통';
        }
    }
</script>

<div class="container-px py-24 md:py-32 space-y-16">
    <!-- Header -->
    <div class="space-y-4">
        <h1 class="text-4xl font-extrabold text-gray-900 tracking-tight flex items-center gap-3">
            <MessageSquare class="w-10 h-10 text-indigo-600" />
            면접 질문 생성
        </h1>
        <p class="text-lg text-gray-500 max-w-2xl">
            작성한 자기소개서와 지원 기업을 분석하여, 면접관이 던질만한 예상 질문과 완벽한 답변 전략을 AI가 준비해 드립니다.
        </p>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        <!-- Input Section (Left) -->
        <div class="lg:col-span-5 space-y-6">
            <div class="bg-white rounded-2xl shadow-xl border border-gray-100 overflow-hidden">
                <div class="p-6 space-y-6">
                    <h2 class="text-xl font-bold text-gray-900 flex items-center gap-2">
                        <FileText class="w-5 h-5 text-indigo-500" />
                        자소서 입력
                    </h2>

                    <!-- Mode Tabs -->
                    <div class="flex p-1 bg-gray-100 rounded-xl space-x-1">
                        {#each [
                            { id: 'text', label: '직접 입력', icon: FileText },
                            { id: 'select', label: '이력 선택', icon: History },
                            { id: 'file', label: '파일 업로드', icon: Upload }
                        ] as mode}
                            <button
                                onclick={() => inputMode = mode.id as any}
                                class="flex-1 flex items-center justify-center gap-2 py-2.5 text-sm font-semibold rounded-lg transition-all
                                {inputMode === mode.id 
                                    ? 'bg-white text-indigo-600 shadow-sm' 
                                    : 'text-gray-500 hover:text-gray-700'}"
                            >
                                <mode.icon class="w-4 h-4" />
                                {mode.label}
                            </button>
                        {/each}
                    </div>

                    <!-- Input Fields -->
                    <div class="space-y-4">
                        {#if inputMode === 'text'}
                            <div class="space-y-2" in:fade>
                                <textarea 
                                    bind:value={manualText} 
                                    rows="8"
                                    class="block w-full rounded-xl border-gray-200 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-4 border bg-gray-50/50"
                                    placeholder="면접 질문을 생성할 자소서 내용을 붙여넣으세요..."
                                ></textarea>
                            </div>
                        {:else if inputMode === 'select'}
                            <div class="space-y-2" in:fade>
                                <select 
                                    bind:value={selectedWritingId}
                                    class="block w-full rounded-xl border-gray-200 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-3 border bg-gray-50/50 appearance-none"
                                >
                                    <option value={undefined}>작성한 이력 선택...</option>
                                    {#each writings as writing}
                                        <option value={writing.id}>
                                            [{writing.itemType || '자유'}] {writing.prompt.slice(0, 30)}...
                                        </option>
                                    {/each}
                                </select>
                            </div>
                        {:else if inputMode === 'file'}
                            <div class="space-y-4" in:fade>
                                <label 
                                    class="flex flex-col items-center justify-center w-full h-48 border-2 border-dashed border-gray-300 rounded-2xl cursor-pointer bg-gray-50 hover:bg-indigo-50 transition-all group"
                                >
                                    <div class="flex flex-col items-center justify-center pt-5 pb-6">
                                        {#if isExtracting}
                                            <Loader2 class="w-10 h-10 text-indigo-500 animate-spin" />
                                            <p class="mt-2 text-sm text-indigo-600 font-medium">분석 중...</p>
                                        {:else}
                                            <BookOpen class="w-10 h-10 text-gray-400 group-hover:text-indigo-500 mb-3 transition-colors" />
                                            <p class="mb-2 text-sm text-gray-700 font-semibold">클릭하여 파일 업로드</p>
                                            <p class="text-xs text-gray-500">PDF, DOCX, 이미지 파일 지원</p>
                                        {/if}
                                    </div>
                                    <input type="file" class="hidden" onchange={handleFileUpload} accept=".pdf,.doc,.docx,image/*" />
                                </label>
                            </div>
                        {/if}
                    </div>

                    <hr class="border-gray-100" />

                    <!-- Options -->
                    <div class="space-y-4">
                        <div class="space-y-2">
                            <label class="block text-sm font-bold text-gray-700 flex items-center gap-2">
                                <Wand2 class="w-4 h-4 text-indigo-500" />
                                면접 답변 스타일
                            </label>
                            <select 
                                bind:value={selectedStyleId}
                                class="block w-full rounded-xl border-gray-200 shadow-sm sm:text-sm p-3 border bg-white"
                            >
                                <option value={undefined}>기본 면접관 스타일</option>
                                {#each styles as style}
                                    <option value={style.id}>{style.name}</option>
                                {/each}
                            </select>
                        </div>

                        <div class="space-y-2">
                            <label class="block text-sm font-bold text-gray-700 flex items-center gap-2">
                                <Building2 class="w-4 h-4 text-indigo-500" />
                                기업 분석 (선택)
                            </label>
                            <select 
                                bind:value={selectedCorporateId}
                                class="block w-full rounded-xl border-gray-200 shadow-sm sm:text-sm p-3 border bg-white"
                            >
                                <option value={undefined}>기업 정보 없음</option>
                                {#each corporates as corp}
                                    <option value={corp.id}>{corp.companyName}</option>
                                {/each}
                            </select>
                        </div>

                        <div class="space-y-2">
                            <label class="block text-sm font-bold text-gray-700">질문 개수</label>
                            <div class="grid grid-cols-4 gap-2">
                                {#each [3, 5, 7, 10] as count}
                                    <button 
                                        onclick={() => questionCount = count}
                                        class="py-2 text-sm font-medium rounded-lg border transition-all
                                        {questionCount === count 
                                            ? 'bg-indigo-600 text-white border-indigo-600 shadow-md' 
                                            : 'bg-white text-gray-600 border-gray-200 hover:border-indigo-300'}"
                                    >
                                        {count}개
                                    </button>
                                {/each}
                            </div>
                        </div>
                    </div>

                    <button 
                        onclick={handleGenerate}
                        disabled={isGenerating || (inputMode === 'text' && !manualText) || (inputMode === 'select' && !selectedWritingId)}
                        class="relative w-full overflow-hidden group py-4 px-6 rounded-2xl shadow-lg transition-all
                        {isGenerating 
                            ? 'bg-gray-100 cursor-not-allowed' 
                            : 'bg-indigo-600 hover:bg-indigo-700 active:scale-[0.98]'}"
                    >
                        {#if isGenerating}
                             <div class="flex items-center justify-center gap-2 text-indigo-600 font-bold">
                                <Loader2 class="w-5 h-5 animate-spin" />
                                면접관이 검토 중...
                             </div>
                        {:else}
                            <div class="flex items-center justify-center gap-2 text-white font-bold text-lg">
                                <Wand2 class="w-5 h-5" />
                                면접 질문 생성하기
                            </div>
                        {/if}
                    </button>

                    {#if error}
                        <div class="flex items-center gap-2 p-4 text-sm text-red-700 bg-red-50 rounded-xl" in:fade>
                            <AlertCircle class="w-5 h-5 flex-shrink-0" />
                            <p>{error}</p>
                        </div>
                    {/if}
                </div>
            </div>
        </div>

        <!-- Result Section (Right) -->
        <div class="lg:col-span-7 space-y-6">
            {#if generatedQuestions.length > 0}
                <div class="flex items-center justify-between border-b border-gray-100 pb-4">
                    <h2 class="text-2xl font-bold text-gray-900">AI 면접 가이드</h2>
                    <span class="text-sm text-gray-500 font-medium">총 {generatedQuestions.length}개의 질문 준비됨</span>
                </div>
                
                <div class="space-y-4">
                    {#each generatedQuestions as q, i}
                        <div 
                            class="bg-white rounded-2xl border border-gray-100 shadow-sm hover:shadow-md transition-all overflow-hidden"
                            in:fade={{ delay: i * 100 }}
                        >
                            <button 
                                onclick={() => expandedIndex = expandedIndex === i ? null : i}
                                class="w-full text-left p-6 flex items-start justify-between gap-4 group"
                            >
                                <div class="flex-1 space-y-2">
                                    <div class="flex items-center gap-2">
                                        <span class="text-xs font-bold text-indigo-600 uppercase tracking-wider bg-indigo-50 px-2 py-0.5 rounded">Q{i+1}</span>
                                        <span class="text-[10px] sm:text-xs font-semibold px-2 py-0.5 rounded-full border {getDifficultyColor(q.difficulty)}">
                                            {getDifficultyLabel(q.difficulty)}
                                        </span>
                                        <span class="text-[10px] sm:text-xs font-semibold px-2 py-0.5 rounded-full bg-blue-50 text-blue-600 border border-blue-100">
                                            {q.category}
                                        </span>
                                    </div>
                                    <h3 class="text-lg font-bold text-gray-900 group-hover:text-indigo-600 transition-colors leading-snug">
                                        {q.question}
                                    </h3>
                                </div>
                                <div class="mt-1">
                                    {#if expandedIndex === i}
                                        <ChevronUp class="w-6 h-6 text-gray-400" />
                                    {:else}
                                        <ChevronDown class="w-6 h-6 text-gray-400 group-hover:text-indigo-500 transition-colors" />
                                    {/if}
                                </div>
                            </button>

                            {#if expandedIndex === i}
                                <div class="px-6 pb-6 pt-0 space-y-5" transition:slide>
                                    <div class="p-5 bg-indigo-50/50 rounded-2xl border border-indigo-100/50 space-y-2">
                                        <h4 class="text-sm font-bold text-indigo-700 flex items-center gap-2">
                                            <Wand2 class="w-4 h-4" />
                                            답변 의도 및 전략
                                        </h4>
                                        <p class="text-sm text-gray-700 leading-relaxed">{q.answerStrategy}</p>
                                    </div>

                                    <div class="p-5 bg-emerald-50/50 rounded-2xl border border-emerald-100/50 space-y-2">
                                        <h4 class="text-sm font-bold text-emerald-700 flex items-center gap-2">
                                            <AlertCircle class="w-4 h-4" />
                                            모범 답변 가이드
                                        </h4>
                                        <p class="text-sm text-gray-800 leading-relaxed whitespace-pre-wrap">{q.suggestedAnswer}</p>
                                    </div>
                                </div>
                            {/if}
                        </div>
                    {/each}
                </div>
            {:else if !isGenerating}
                <!-- Empty State -->
                <div class="bg-white h-[600px] flex flex-col items-center justify-center text-center p-12 rounded-3xl border border-gray-100 shadow-sm" in:fade>
                    <div class="relative mb-6">
                        <div class="absolute inset-0 bg-indigo-100 rounded-full blur-3xl opacity-50 scale-150"></div>
                        <div class="relative bg-white p-6 rounded-full shadow-lg border border-gray-50">
                            <MessageSquare class="h-16 w-16 text-indigo-500" />
                        </div>
                    </div>
                    <h3 class="text-2xl font-extrabold text-gray-900 mb-2">당신만을 위한 면접 파트너</h3>
                    <p class="text-gray-500 max-w-sm leading-relaxed mb-8">
                        왼쪽에서 자소서 내용을 입력하거나 작성한 기록을 선택하시면, 
                        AI가 수만 개의 합격 답변 데이터를 바탕으로 최적의 질문을 뽑아드립니다.
                    </p>
                    <div class="grid grid-cols-3 gap-4 w-full max-w-md">
                        <div class="flex flex-col items-center gap-2">
                            <div class="w-10 h-10 rounded-full bg-blue-50 flex items-center justify-center">
                                <FileText class="w-5 h-5 text-blue-600" />
                            </div>
                            <span class="text-xs font-bold text-gray-600 uppercase">자소서 분석</span>
                        </div>
                        <div class="flex flex-col items-center gap-2">
                            <div class="w-10 h-10 rounded-full bg-indigo-50 flex items-center justify-center">
                                <Building2 class="w-5 h-5 text-indigo-600" />
                            </div>
                            <span class="text-xs font-bold text-gray-600 uppercase">기업 맞춤</span>
                        </div>
                        <div class="flex flex-col items-center gap-2">
                            <div class="w-10 h-10 rounded-full bg-emerald-50 flex items-center justify-center">
                                <Wand2 class="w-5 h-5 text-emerald-600" />
                            </div>
                            <span class="text-xs font-bold text-gray-600 uppercase">전략 답변</span>
                        </div>
                    </div>
                </div>
            {:else}
                <!-- Generating State -->
                <div class="bg-white h-[600px] flex flex-col items-center justify-center text-center p-12 rounded-3xl border border-gray-100 shadow-sm" in:fade>
                    <div class="relative mb-8">
                        <div class="absolute inset-0 bg-indigo-400 rounded-full blur-2xl opacity-20 animate-pulse"></div>
                        <Loader2 class="h-20 w-20 text-indigo-600 animate-spin relative" />
                    </div>
                    <h3 class="text-2xl font-extrabold text-gray-900 mb-2">면접관이 내용을 분석 중입니다</h3>
                    <p class="text-gray-500 max-w-sm leading-relaxed">
                        자소서의 핵심 키워드를 추출하고 기업 인재상을 대조하고 있습니다. 잠시만 기다려 주세요...
                    </p>
                </div>
            {/if}
        </div>
    </div>
</div>

<style>
    /* Custom scrollbar for better look */
    :global(::-webkit-scrollbar) {
        width: 8px;
    }
    :global(::-webkit-scrollbar-track) {
        background: transparent;
    }
    :global(::-webkit-scrollbar-thumb) {
        background: #e2e8f0;
        border-radius: 10px;
    }
    :global(::-webkit-scrollbar-thumb:hover) {
        background: #cbd5e1;
    }
</style>

// front/client/src/pages/Interview.tsx
import { useState } from 'react';
import { MessageSquare, Wand2, ChevronDown, ChevronUp, BookOpen, Building2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import Navbar from '@/components/Navbar';
import { toast } from 'sonner';
import { trpc } from '@/lib/api';

interface Question {
    question: string;
    suggestedAnswer: string;
    answerStrategy: string;
    category: string;
    difficulty: 'easy' | 'medium' | 'hard';
}

export default function Interview() {
    const [inputMode, setInputMode] = useState<'select' | 'text' | 'file'>('text');
    const [coverLetterText, setCoverLetterText] = useState('');
    const [selectedWritingId, setSelectedWritingId] = useState<number | undefined>();
    const [selectedInterviewStyleId, setSelectedInterviewStyleId] = useState<number | undefined>();
    const [selectedCorporateId, setSelectedCorporateId] = useState<number | undefined>();
    const [questionCount, setQuestionCount] = useState(5);
    const [questions, setQuestions] = useState<Question[]>([]);
    const [expandedIndex, setExpandedIndex] = useState<number | null>(null);

    // tRPC queries
    const { data: writingHistory = [] } = trpc.writing.getHistory.useQuery(undefined, { retry: false });
    const { data: interviewStyles = [] } = trpc.interviewLearning.listStyles.useQuery(undefined, { retry: false });
    const { data: corporates = [] } = trpc.corporate.list.useQuery(undefined, { retry: false });

    const generateMutation = trpc.interview.generateQuestions.useMutation({
        onSuccess: (data) => {
            setQuestions(data.questions);
            toast.success(`${data.questions.length}개의 면접 질문이 생성되었습니다!`);
        },
        onError: (error) => {
            toast.error(error.message || '질문 생성 실패');
        }
    });

    const handleGenerate = () => {
        if (inputMode === 'text' && !coverLetterText.trim()) {
            toast.error('자소서 내용을 입력해주세요.');
            return;
        }
        if (inputMode === 'select' && !selectedWritingId) {
            toast.error('자소서를 선택해주세요.');
            return;
        }

        generateMutation.mutate({
            writingId: inputMode === 'select' ? selectedWritingId : undefined,
            coverLetterText: inputMode === 'text' ? coverLetterText : undefined,
            interviewStyleId: selectedInterviewStyleId,
            corporateId: selectedCorporateId,
            questionCount,
        });
    };

    const getDifficultyColor = (difficulty: string) => {
        switch (difficulty) {
            case 'easy': return 'bg-green-100 text-green-700';
            case 'medium': return 'bg-yellow-100 text-yellow-700';
            case 'hard': return 'bg-red-100 text-red-700';
            default: return 'bg-gray-100 text-gray-700';
        }
    };

    const getDifficultyLabel = (difficulty: string) => {
        switch (difficulty) {
            case 'easy': return '기본';
            case 'medium': return '중급';
            case 'hard': return '심화';
            default: return difficulty;
        }
    };

    return (
        <div className="min-h-screen bg-background">
            <Navbar />
            <div className="container mx-auto px-4 py-24">
                <h1 className="text-4xl font-bold mb-4 flex items-center gap-3">
                    <MessageSquare className="w-10 h-10 text-accent" />
                    면접 질문 생성
                </h1>
                <p className="text-lg text-muted-foreground mb-8">
                    자소서를 분석하여 예상 면접 질문과 답변 전략을 제공합니다.
                </p>

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                    {/* Input Section */}
                    <div className="bg-card p-6 rounded-lg border border-border shadow-sm">
                        <h2 className="text-xl font-semibold mb-4">자소서 입력</h2>

                        {/* Input Mode Toggle */}
                        <div className="flex gap-2 mb-4">
                            <Button
                                variant={inputMode === 'text' ? 'default' : 'outline'}
                                size="sm"
                                onClick={() => setInputMode('text')}
                            >
                                직접 입력
                            </Button>
                            <Button
                                variant={inputMode === 'select' ? 'default' : 'outline'}
                                size="sm"
                                onClick={() => setInputMode('select')}
                            >
                                작성 이력에서 선택
                            </Button>
                            <Button
                                variant={inputMode === 'file' ? 'default' : 'outline'}
                                size="sm"
                                onClick={() => setInputMode('file')}
                            >
                                이력서 파일 업로드
                            </Button>
                        </div>

                        {inputMode === 'text' && (
                            <Textarea
                                className="min-h-[200px] mb-4"
                                placeholder="면접 질문을 생성할 자소서 내용을 입력하세요..."
                                value={coverLetterText}
                                onChange={(e) => setCoverLetterText(e.target.value)}
                            />
                        )}

                        {inputMode === 'select' && (
                            <select
                                className="w-full p-3 rounded-md border border-gray-300 bg-background mb-4"
                                value={selectedWritingId || ''}
                                onChange={(e) => setSelectedWritingId(e.target.value ? parseInt(e.target.value) : undefined)}
                            >
                                <option value="">자소서 선택...</option>
                                {writingHistory.map((history) => (
                                    <option key={history.id} value={history.id}>
                                        {history.itemType || '자유양식'} - {history.prompt?.substring(0, 30)}... ({new Date(history.createdAt).toLocaleDateString('ko-KR')})
                                    </option>
                                ))}
                            </select>
                        )}

                        {inputMode === 'file' && (
                            <div className="border-2 border-dashed border-gray-300 rounded-lg p-6 mb-4 text-center hover:bg-accent/5 transition-colors">
                                <input
                                    type="file"
                                    id="resume-upload"
                                    className="hidden"
                                    accept=".pdf,.docx,.doc,image/*"
                                    onChange={async (e) => {
                                        const file = e.target.files?.[0];
                                        if (!file) return;

                                        const formData = new FormData();
                                        formData.append('file', file);

                                        const loadingToast = toast.loading('파일 분석 중...');

                                        try {
                                            const response = await fetch('/api/analysis/upload/extract', {
                                                method: 'POST',
                                                body: formData,
                                            });

                                            if (!response.ok) throw new Error('업로드 실패');

                                            const data = await response.json();
                                            setCoverLetterText(data.text);
                                            toast.dismiss(loadingToast);
                                            toast.success('이력서 내용이 추출되었습니다!');
                                            // Switch to text mode to show/edit extracted text
                                            setInputMode('text');
                                        } catch (error) {
                                            console.error(error);
                                            toast.dismiss(loadingToast);
                                            toast.error('파일 분석에 실패했습니다.');
                                        }
                                    }}
                                />
                                <label htmlFor="resume-upload" className="cursor-pointer flex flex-col items-center gap-2">
                                    <BookOpen className="w-8 h-8 text-muted-foreground" />
                                    <span className="text-sm font-medium">
                                        클릭하여 파일 업로드 (PDF, DOCX, 이미지)
                                    </span>
                                    <span className="text-xs text-muted-foreground">
                                        파일을 올리면 내용을 자동으로 분석하여 입력창에 채워줍니다.
                                    </span>
                                </label>
                            </div>
                        )}

                        {/* Options */}
                        <div className="space-y-4">
                            <div>
                                <label className="block text-sm font-medium mb-1">면접 답변 스타일 (선택)</label>
                                <select
                                    className="w-full p-2 rounded-md border border-gray-300 bg-background"
                                    value={selectedInterviewStyleId || ''}
                                    onChange={(e) => setSelectedInterviewStyleId(e.target.value ? parseInt(e.target.value) : undefined)}
                                >
                                    <option value="">기본 스타일</option>
                                    {interviewStyles.map((style) => (
                                        <option key={style.id} value={style.id}>{style.name}</option>
                                    ))}
                                </select>
                            </div>

                            <div>
                                <label className="block text-sm font-medium mb-1">기업 분석 (선택)</label>
                                <div className="relative">
                                    <Building2 className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" />
                                    <select
                                        className="w-full p-2 pl-9 rounded-md border border-gray-300 bg-background"
                                        value={selectedCorporateId || ''}
                                        onChange={(e) => setSelectedCorporateId(e.target.value ? parseInt(e.target.value) : undefined)}
                                    >
                                        <option value="">선택 안 함</option>
                                        {corporates.map((corp: any) => (
                                            <option key={corp.id} value={corp.id}>
                                                {corp.companyName} ({new Date(corp.createdAt).toLocaleDateString()})
                                            </option>
                                        ))}
                                    </select>
                                </div>
                            </div>

                            <div>
                                <label className="block text-sm font-medium mb-1">생성할 질문 개수</label>
                                <select
                                    className="w-full p-2 rounded-md border border-gray-300 bg-background"
                                    value={questionCount}
                                    onChange={(e) => setQuestionCount(parseInt(e.target.value))}
                                >
                                    <option value={3}>3개</option>
                                    <option value={5}>5개</option>
                                    <option value={7}>7개</option>
                                    <option value={10}>10개</option>
                                </select>
                            </div>

                            <Button
                                onClick={handleGenerate}
                                disabled={generateMutation.isPending}
                                className="w-full gap-2"
                            >
                                <Wand2 className="w-4 h-4" />
                                {generateMutation.isPending ? 'AI가 질문 생성 중...' : '면접 질문 생성'}
                            </Button>
                        </div>
                    </div>

                    {/* Results Section */}
                    <div className="bg-card p-6 rounded-lg border border-border shadow-sm">
                        <h2 className="text-xl font-semibold mb-4">
                            생성된 질문 ({questions.length}개)
                        </h2>

                        {questions.length === 0 ? (
                            <div className="text-center py-16 text-muted-foreground">
                                <BookOpen className="w-12 h-12 mx-auto mb-4 opacity-50" />
                                <p>왼쪽에서 자소서를 입력하고</p>
                                <p>면접 질문을 생성해보세요!</p>
                            </div>
                        ) : (
                            <div className="space-y-4 max-h-[600px] overflow-y-auto">
                                {questions.map((q, idx) => (
                                    <div
                                        key={idx}
                                        className="border border-gray-200 rounded-lg overflow-hidden"
                                    >
                                        {/* Question Header */}
                                        <div
                                            className="p-4 bg-gray-50 cursor-pointer flex items-center justify-between"
                                            onClick={() => setExpandedIndex(expandedIndex === idx ? null : idx)}
                                        >
                                            <div className="flex-1">
                                                <div className="flex items-center gap-2 mb-1">
                                                    <span className="text-sm font-medium text-accent">Q{idx + 1}</span>
                                                    <span className={`text-xs px-2 py-0.5 rounded-full ${getDifficultyColor(q.difficulty)}`}>
                                                        {getDifficultyLabel(q.difficulty)}
                                                    </span>
                                                    <span className="text-xs px-2 py-0.5 rounded-full bg-blue-100 text-blue-700">
                                                        {q.category}
                                                    </span>
                                                </div>
                                                <p className="font-medium">{q.question}</p>
                                            </div>
                                            {expandedIndex === idx ? (
                                                <ChevronUp className="w-5 h-5 text-gray-400" />
                                            ) : (
                                                <ChevronDown className="w-5 h-5 text-gray-400" />
                                            )}
                                        </div>

                                        {/* Expanded Content */}
                                        {expandedIndex === idx && (
                                            <div className="p-4 border-t border-gray-200 space-y-4">
                                                <div>
                                                    <h4 className="text-sm font-semibold text-green-600 mb-2">💡 모범 답변 예시</h4>
                                                    <p className="text-sm text-gray-700 bg-green-50 p-3 rounded-lg">
                                                        {q.suggestedAnswer}
                                                    </p>
                                                </div>
                                                <div>
                                                    <h4 className="text-sm font-semibold text-blue-600 mb-2">📋 답변 전략 및 팁</h4>
                                                    <p className="text-sm text-gray-700 bg-blue-50 p-3 rounded-lg">
                                                        {q.answerStrategy}
                                                    </p>
                                                </div>
                                            </div>
                                        )}
                                    </div>
                                ))}
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}
