// front/client/src/pages/Writing.tsx
import { useState, useEffect } from 'react';
import { getApiUrl } from "@/config";
import Navbar from '@/components/Navbar';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';
import { PenTool, Wand2, FileText, Building2 } from 'lucide-react';
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from "@/components/ui/dialog";
import { trpc } from '@/lib/api';

export default function Writing() {
    const [prompt, setPrompt] = useState('');
    const [selectedStyleId, setSelectedStyleId] = useState<number | undefined>();
    const [selectedExperienceId, setSelectedExperienceId] = useState<number | undefined>();
    const [selectedCorporateId, setSelectedCorporateId] = useState<number | undefined>();
    const [result, setResult] = useState('');
    const [itemType, setItemType] = useState('자유양식');
    const [targetCharCount, setTargetCharCount] = useState<number>(1000);

    // JD Analysis Context
    const [jdContext, setJdContext] = useState<{ keywords: string[], summary: string } | null>(null);
    const [isJdDialogOpen, setIsJdDialogOpen] = useState(false);
    const [analysisIdInput, setAnalysisIdInput] = useState("");

    // tRPC hooks
    const { data: styles = [] } = trpc.writingLearning.listStyles.useQuery(undefined, {
        retry: false,
        enabled: true,
    });
    const { data: experiences = [] } = trpc.experiences.list.useQuery(undefined, {
        retry: false,
        enabled: true,
    });
    const { data: corporates = [] } = trpc.corporate.list.useQuery(undefined, {
        retry: false,
        enabled: true,
    });
    const generateMutation = trpc.writing.generate.useMutation();

    // Character Count State
    const [charCount, setCharCount] = useState({
        total: 0,
        noSpace: 0,
        bytes: 0
    });

    /**
     * 문자 하나의 바이트 수를 계산합니다.
     * - UTF-8 기준: 한글 3바이트, 기타 다국어 문자 2~4바이트
     * - EUC-KR 기준: 한글/한자 2바이트 (채용사이트 표준)
     * @param byteMode 'euckr' | 'utf8'
     */
    const getCharBytes = (charCode: number, byteMode: 'euckr' | 'utf8'): number => {
        if (charCode <= 0x7F) return 1; // ASCII
        if (byteMode === 'euckr') {
            // EUC-KR: 한글·한자·전각기호 등 0x80 이상은 2바이트
            return 2;
        }
        // UTF-8
        if (charCode <= 0x7FF) return 2;
        if (charCode <= 0xFFFF) return 3;
        return 4;
    };

    const calculateCounts = (text: string) => {
        const total = text.length;
        const noSpace = text.replace(/\s/g, '').length;

        // 채용사이트 표준(EUC-KR 2byte) 기준 바이트 수
        let bytes = 0;
        for (let i = 0; i < text.length; i++) {
            bytes += getCharBytes(text.charCodeAt(i), 'euckr');
        }

        setCharCount({ total, noSpace, bytes });
    };

    // Update counts when result changes
    useEffect(() => {
        calculateCounts(result);
    }, [result]);



    const fetchJdAnalysis = async () => {
        if (!analysisIdInput) return;
        try {
            const res = await fetch(getApiUrl(`/api/analysis/${analysisIdInput}`));
            if (res.ok) {
                const data = await res.json();
                if (data.analysis_result) {
                    setJdContext({
                        keywords: data.analysis_result.talent_keywords || [],
                        summary: data.analysis_result.job_summary || ""
                    });
                    toast.success("JD 분석 내용을 불러왔습니다.");
                    setIsJdDialogOpen(false);
                } else {
                    toast.error("아직 분석이 완료되지 않았습니다.");
                }
            } else {
                toast.error("분석 결과를 찾을 수 없습니다.");
            }
        } catch (e) {
            console.error(e);
            toast.error("불러오기 실패");
        }
    };

    // Set default style when styles load
    useEffect(() => {
        if (styles.length > 0 && !selectedStyleId) {
            setSelectedStyleId(styles[0].id);
        }
    }, [styles, selectedStyleId]);

    const handleGenerate = async () => {
        if (!prompt.trim()) return;

        try {
            const data = await generateMutation.mutateAsync({
                prompt,
                styleId: selectedStyleId,
                itemType,
                targetCharCount,
                experienceId: selectedExperienceId,
                corporateId: selectedCorporateId,
                context: {
                    jd_keywords: jdContext?.keywords,
                    jd_summary: jdContext?.summary,
                },
            });

            setResult(data.generatedText);
            const charDiff = data.actualCharCount - (data.targetCharCount || 0);
            const diffPercent = data.targetCharCount
                ? Math.abs(charDiff / data.targetCharCount * 100).toFixed(1)
                : 0;

            // Show similarity score if available
            const similarityMsg = data.styleSimilarity
                ? `\n스타일 일치도: ${data.styleSimilarity}%`
                : '';
            const similarityEmoji = data.styleSimilarity && data.styleSimilarity >= 30 ? '✅' : data.styleSimilarity ? '⚠️' : '';

            toast.success(
                `${similarityEmoji} 작성 완료!\n목표: ${data.targetCharCount}자 / 실제: ${data.actualCharCount}자${similarityMsg}`
            );
        } catch (e: any) {
            console.error(e);
            toast.error(e.message || "생성 실패");
        }
    };

    return (
        <div className="min-h-screen bg-background">
            <Navbar />
            <div className="container mx-auto px-4 py-24 pb-12">
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                    {/* Left: Input */}
                    <div className="flex flex-col gap-4">
                        <div className="flex items-center justify-between">
                            <h1 className="text-2xl font-bold flex items-center gap-2">
                                <PenTool className="w-6 h-6 text-accent" />
                                자기소개서 작성
                            </h1>
                        </div>
                        <div className="bg-card rounded-lg border border-border p-6 shadow-sm flex flex-col gap-4">

                            {/* Item Type */}
                            <div>
                                <label className="text-sm font-medium mb-1 block text-muted-foreground">항목 유형</label>
                                <select
                                    className="w-full p-2 rounded-md border border-gray-300 bg-background"
                                    value={itemType.startsWith('custom:') ? 'custom' : itemType}
                                    onChange={(e) => {
                                        if (e.target.value === 'custom') {
                                            setItemType('custom:');
                                        } else {
                                            setItemType(e.target.value);
                                        }
                                    }}
                                >
                                    <option value="지원동기">지원동기</option>
                                    <option value="입사후포부">입사 후 포부</option>
                                    <option value="성장과정">성장과정</option>
                                    <option value="성격의장단점">성격의 장단점</option>
                                    <option value="직무역량">직무 역량/경험</option>
                                    <option value="자유양식">자유양식</option>
                                    <option value="custom">📝 직접입력</option>
                                </select>
                            </div>

                            {/* Custom Item Type Input */}
                            {itemType.startsWith('custom:') && (
                                <div className="animate-in slide-in-from-top-2">
                                    <label className="text-sm font-medium mb-1 block text-muted-foreground">
                                        실제 자소서 항목 (질문)
                                    </label>
                                    <Textarea
                                        className="min-h-[80px] resize-none"
                                        placeholder="예: 본인이 겪은 가장 큰 도전과 그 경험을 통해 배운 점을 기술해 주세요. (500자 이내)"
                                        value={itemType.replace('custom:', '')}
                                        onChange={(e) => setItemType(`custom:${e.target.value}`)}
                                    />
                                    <p className="text-xs text-muted-foreground mt-1">
                                        실제 지원하는 회사의 자소서 항목을 그대로 입력하면 더 정확한 답변이 생성됩니다.
                                    </p>
                                </div>
                            )}

                            {/* Target Character Count */}
                            <div>
                                <label className="text-sm font-medium mb-1 block text-muted-foreground">목표 글자수</label>
                                <input
                                    type="number"
                                    className="w-full p-2 rounded-md border border-gray-300 bg-background"
                                    value={targetCharCount}
                                    onChange={(e) => setTargetCharCount(parseInt(e.target.value) || 1000)}
                                    min={100}
                                    max={3000}
                                    step={100}
                                />
                            </div>

                            {/* Style Selection */}
                            <div>
                                <label className="text-sm font-medium mb-1 block text-muted-foreground">스타일 선택 (선택사항)</label>
                                <select
                                    className="w-full p-2 rounded-md border border-gray-300 bg-background"
                                    value={selectedStyleId || ''}
                                    onChange={(e) => setSelectedStyleId(e.target.value ? parseInt(e.target.value) : undefined)}
                                >
                                    <option value="">기본 스타일</option>
                                    {styles.map(s => (
                                        <option key={s.id} value={s.id}>{s.name}</option>
                                    ))}
                                </select>
                            </div>

                            {/* Experience Selection */}
                            <div>
                                <label className="text-sm font-medium mb-1 block text-muted-foreground">경험 소재 선택 (선택사항)</label>
                                <select
                                    className="w-full p-2 rounded-md border border-gray-300 bg-background"
                                    value={selectedExperienceId || ''}
                                    onChange={(e) => setSelectedExperienceId(e.target.value ? parseInt(e.target.value) : undefined)}
                                >
                                    <option value="">선택 안 함 (직접 입력)</option>
                                    {experiences.map((exp: any) => {
                                        // analysis column is already JSON type in DB/Drizzle
                                        // but handled as unknown/any in frontend due to loose typing
                                        const analysis = exp.analysis as any;
                                        const label = analysis?.summary
                                            ? `[${analysis.category || '기타'}] ${analysis.summary.substring(0, 30)}...`
                                            : analysis?.situation
                                                ? `[${analysis.category || '기타'}] ${analysis.situation.substring(0, 30)}...`
                                                : exp.title;

                                        return (
                                            <option key={exp.id} value={exp.id}>
                                                {label}
                                            </option>
                                        );
                                    })}
                                </select>
                                {selectedExperienceId && (
                                    <p className="text-xs text-muted-foreground mt-1">
                                        선택한 경험의 분석 내용(STAR 기법)이 프롬프트에 자동으로 포함됩니다.
                                    </p>
                                )}
                            </div>

                            {/* Corporate Analysis Selection */}
                            <div>
                                <label className="text-sm font-medium mb-1 block text-muted-foreground">기업 분석 선택 (선택사항)</label>
                                <div className="relative">
                                    <Building2 className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" />
                                    <select
                                        className="w-full p-2 pl-9 rounded-md border border-gray-300 bg-background"
                                        value={selectedCorporateId || ''}
                                        onChange={(e) => setSelectedCorporateId(e.target.value ? parseInt(e.target.value) : undefined)}
                                    >
                                        <option value="">선택 안 함</option>
                                        {corporates.map((corp: any) => (
                                            <option key={corp.id} value={corp.id}>
                                                {corp.companyName} ({new Date(corp.createdAt).toLocaleDateString()})
                                            </option>
                                        ))}
                                    </select>
                                </div>
                                {selectedCorporateId && (
                                    <p className="text-xs text-muted-foreground mt-1">
                                        기업의 인재상/핵심가치/최신이슈가 반영되어 작성됩니다.
                                    </p>
                                )}
                            </div>

                            <label className="font-medium text-muted-foreground">어떤 자소서를 쓰고 싶으신가요?</label>
                            <Textarea
                                placeholder="예: 마케팅 직무 지원동기를 작성해줘. 강조하고 싶은 점은 창의적인 문제 해결 능력이야."
                                className="flex-1 resize-none text-lg p-4"
                                value={prompt}
                                onChange={(e) => setPrompt(e.target.value)}
                            />
                            <div className="flex gap-2 w-full">
                                <Button
                                    variant="outline"
                                    onClick={() => setIsJdDialogOpen(true)}
                                    className="gap-2 flex-1 hover:bg-muted text-accent"
                                >
                                    <FileText className="w-4 h-4" />
                                    {jdContext ? "JD 적용됨" : "JD 불러오기"}
                                </Button>
                                <Button
                                    onClick={handleGenerate}
                                    disabled={generateMutation.isPending}
                                    className="gap-2 flex-1 bg-primary hover:bg-primary/90 text-white"
                                >
                                    <Wand2 className="w-5 h-5" />
                                    {generateMutation.isPending ? 'AI가 작성 중...' : 'AI로 생성하기'}
                                </Button>
                            </div>

                            <Dialog open={isJdDialogOpen} onOpenChange={setIsJdDialogOpen}>
                                <DialogContent>
                                    <DialogHeader>
                                        <DialogTitle>JD 분석 결과 불러오기</DialogTitle>
                                    </DialogHeader>
                                    <div className="space-y-4 py-4">
                                        <p className="text-sm text-gray-500">
                                            'JD 분석' 페이지에서 분석한 ID를 입력하세요.
                                            (추후 리스트 선택으로 개선 예정)
                                        </p>
                                        <div className="flex gap-2">
                                            <input
                                                className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background"
                                                placeholder="분석 ID 입력 (예: 1)"
                                                value={analysisIdInput}
                                                onChange={(e) => setAnalysisIdInput(e.target.value)}
                                            />
                                            <Button onClick={fetchJdAnalysis}>불러오기</Button>
                                        </div>
                                    </div>
                                </DialogContent>
                            </Dialog>
                        </div>
                    </div>

                    {/* Right: Output */}
                    <div className="flex flex-col gap-4">
                        <h2 className="text-2xl font-bold text-gray-400">결과물</h2>
                        <div className="bg-white rounded-lg border border-border p-8 shadow-sm max-h-[600px] overflow-y-auto whitespace-pre-wrap">
                            {result ? (
                                <div className="prose max-w-none">
                                    {result}
                                </div>
                            ) : (
                                <div className="h-64 flex items-center justify-center text-muted-foreground text-center">
                                    <p>왼쪽에서 내용을 입력하고<br />생성 버튼을 눌러주세요.</p>
                                </div>
                            )}
                        </div>
                    </div>

                    {/* Character Counter Footer */}
                    <div className="bg-gray-50 border-t p-4 flex justify-between items-center text-sm text-gray-600">
                        <div className="flex gap-4">
                            <span>공백포함 <strong className="text-gray-900">{charCount.total}</strong>자</span>
                            <span>공백제외 <strong className="text-gray-900">{charCount.noSpace}</strong>자</span>
                        </div>
                        <div>
                            <span className="text-gray-400">|</span>
                            <span className="ml-4"><strong className="text-gray-900">{charCount.bytes}</strong> bytes</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

// front-svelte/src/routes/writing/+page.svelte
<script lang="ts">
    import { trpc } from '$lib/trpc';
    import { page } from '$app/stores';
    
    let prompt = $state('');
    let targetCharCount = $state(500);
    let companyName = $state('');
    let jobCategory = $state('');
    let selectedExperienceId = $state<number | undefined>(undefined);
    let selectedStyleId = $state<number | undefined>(undefined);
    let generatedText = $state('');
    let isGenerating = $state(false);
    let error = $state('');
    let charCount = $derived.by(() => {
        const text = generatedText || '';
        const total = text.length;
        const noSpace = text.replace(/\s/g, '').length;
        let bytes = 0;
        for (let i = 0; i < text.length; i++) {
            bytes += text.charCodeAt(i) > 127 ? 2 : 1;
        }
        return { total, noSpace, bytes };
    });

    // Pre-load data
    let styles = $state<any[]>([]);
    let experiences = $state<any[]>([]);
    
    let jdContext = $state<{ keywords: string[], summary: string } | null>(null);
    let analysisIdInput = $state('');
    let showJdModal = $state(false);

    $effect(() => {
        const client = trpc($page);
        client.writingLearning.listStyles.query().then(res => styles = res);
        client.experiences.list.query().then(res => experiences = res);
    });

    async function fetchJdAnalysis() {
        if (!analysisIdInput) return;
        try {
            const res = await fetch(`/api/analysis/${analysisIdInput}`);
            if (res.ok) {
                const data = await res.json();
                if (data.analysis_result) {
                    jdContext = {
                        keywords: data.analysis_result.talent_keywords || [],
                        summary: data.analysis_result.job_summary || ""
                    };
                    showJdModal = false;
                    alert("JD 분석 내용을 불러왔습니다.");
                } else {
                    alert("아직 분석이 완료되지 않았습니다.");
                }
            } else {
                alert("분석 결과를 찾을 수 없습니다.");
            }
        } catch (e) {
            alert("불러오기 실패");
        }
    }

    async function handleGenerate() {
        if (!prompt) return;
        isGenerating = true;
        error = '';
        generatedText = '';

        try {
            const result = await trpc($page).writing.generate.mutate({
                prompt,
                targetCharCount,
                styleId: selectedStyleId,
                experienceId: selectedExperienceId, // Pass selected experience
                itemType: '자기소개서',
                companyName: companyName || undefined,
                jobCategory: jobCategory || undefined
            });
            generatedText = result.generatedText;
        } catch (e: any) {
            console.error(e);
            error = e.message || 'Generation failed';
        } finally {
            isGenerating = false;
        }
    }
</script>

<div class="container-px py-24 md:py-32 space-y-12">
    <div class="space-y-2">
        <h1 class="text-3xl font-bold text-gray-900">자기소개서 생성</h1>
        <p class="text-gray-500">AI가 당신의 경험을 바탕으로 맞춤형 자기소개서를 작성해드립니다.</p>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
        <!-- Input Section -->
        <div class="md:col-span-1 space-y-6">
            <div class="space-y-2">
                <label for="prompt" class="block text-sm font-medium text-gray-700">작성할 항목 / 질문</label>
                <textarea 
                    id="prompt" 
                    bind:value={prompt} 
                    rows="6"
                    class="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-3 border"
                    placeholder="예: 지원동기, 입사 후 포부, 성격의 장단점..."
                ></textarea>
            </div>

            <div class="space-y-2">
                <label for="experience" class="block text-sm font-medium text-gray-700">활용할 경험 (STAR)</label>
                <select 
                    id="experience" 
                    bind:value={selectedExperienceId}
                    class="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2 border"
                >
                    <option value={undefined}>경험 선택 안함 (일반 작성)</option>
                    {#each experiences as exp}
                        <option value={exp.id}>{exp.title}</option>
                    {/each}
                </select>
                {#if experiences.length === 0}
                    <p class="text-xs text-gray-500">
                        <a href="/dashboard/experience/new" class="text-indigo-600 hover:underline">새 경험 추가하기</a>에서 경험을 먼저 정리해보세요.
                    </p>
                {/if}
            </div>

            <div class="space-y-4 pt-4 border-t border-gray-200">
                <h3 class="text-sm font-medium text-gray-900">부가 정보 (데이터 분석용)</h3>
                <div class="grid grid-cols-2 gap-4">
                    <div>
                        <label for="companyName" class="block text-xs font-medium text-gray-500">기업명</label>
                        <input 
                            type="text" 
                            id="companyName" 
                            bind:value={companyName} 
                            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2 border"
                            placeholder="예: 삼성전자"
                        />
                    </div>
                    <div>
                        <label for="jobCategory" class="block text-xs font-medium text-gray-500">직무</label>
                        <input 
                            type="text" 
                            id="jobCategory" 
                            bind:value={jobCategory} 
                            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2 border"
                            placeholder="예: 마케팅 / 개발"
                        />
                    </div>
                </div>
            </div>

            <div class="space-y-2">
                <label for="style" class="block text-sm font-medium text-gray-700">글쓰기 스타일</label>
                <select 
                    id="style" 
                    bind:value={selectedStyleId}
                    class="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2 border"
                >
                    <option value={undefined}>기본 스타일</option>
                    {#each styles as style}
                        <option value={style.id}>{style.name}</option>
                    {/each}
                </select>
            </div>

            <div class="space-y-2">
                <label for="count" class="block text-sm font-medium text-gray-700">목표 글자수 (공백포함)</label>
                <input 
                    type="number" 
                    id="count" 
                    bind:value={targetCharCount} 
                    step="100" 
                    min="100" 
                    max="2000"
                    class="block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm p-2 border"
                />
            </div>

            <div class="flex flex-col gap-2">
                <button 
                    onclick={() => showJdModal = true}
                    class="w-full py-2 px-4 border border-indigo-200 text-indigo-600 rounded-md text-sm font-bold hover:bg-indigo-50 transition-colors flex items-center justify-center gap-2"
                >
                    <FileText class="w-4 h-4" />
                    {jdContext ? "JD 분석 적용됨" : "JD 분석 불러오기"}
                </button>

                <button 
                    onclick={handleGenerate}
                    disabled={isGenerating || !prompt}
                    class="w-full flex justify-center py-3 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50"
                >
                    {#if isGenerating}
                        생성 중...
                    {:else}
                        자기소개서 생성
                    {/if}
                </button>
            </div>
            
            {#if error}
                <p class="text-red-500 text-sm">{error}</p>
            {/if}
        </div>

        <!-- JD Modal -->
        {#if showJdModal}
            <div class="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4" transition:fade>
                <div class="bg-white rounded-2xl p-8 max-w-md w-full space-y-6 shadow-2xl" in:fly={{ y: 20 }}>
                    <div class="flex justify-between items-center">
                        <h3 class="text-xl font-bold text-gray-900">JD 분석 불러오기</h3>
                        <button onclick={() => showJdModal = false} class="text-gray-400 hover:text-gray-600"><X class="w-6 h-6" /></button>
                    </div>
                    <p class="text-sm text-gray-500">
                        'JD 분석' 페이지에서 생성된 분석 ID를 입력해 주세요. 분석 내용을 바탕으로 자소서가 작성됩니다.
                    </p>
                    <div class="flex gap-2">
                        <input 
                            type="text" 
                            bind:value={analysisIdInput} 
                            placeholder="분석 ID 입력 (예: 1)" 
                            class="flex-1 rounded-xl border-gray-200 border p-3 text-sm focus:ring-2 focus:ring-indigo-500 outline-none" 
                        />
                        <button 
                            onclick={fetchJdAnalysis}
                            class="px-6 py-2 bg-indigo-600 text-white rounded-xl font-bold hover:bg-indigo-700 transition-all shadow-lg active:scale-95"
                        >
                            불러오기
                        </button>
                    </div>
                     {#if jdContext}
                        <div class="p-4 bg-emerald-50 rounded-xl border border-emerald-100 flex items-start gap-3">
                            <CheckCircle2 class="w-5 h-5 text-emerald-500 shrink-0 mt-0.5" />
                            <div>
                                <p class="text-xs font-bold text-emerald-700 uppercase tracking-widest">분석 데이터 로드됨</p>
                                <p class="text-[11px] text-emerald-600 line-clamp-2 mt-1">{jdContext.summary}</p>
                            </div>
                        </div>
                    {/if}
                </div>
            </div>
        {/if}

        <!-- Output Section -->
        <div class="md:col-span-2 bg-gray-50 rounded-lg p-6 border border-gray-200 min-h-[500px]">
            {#if generatedText}
                <div class="prose max-w-none whitespace-pre-wrap leading-relaxed text-gray-800">
                    {generatedText}
                </div>
                <div class="mt-4 pt-4 border-t border-gray-200 flex flex-col sm:flex-row justify-between items-center gap-4 text-xs font-bold text-gray-400 uppercase tracking-widest">
                    <div class="flex gap-6">
                        <span class="flex items-center gap-1.5">공백포함 <strong class="text-gray-900">{charCount.total}</strong>자</span>
                        <span class="flex items-center gap-1.5">공백제외 <strong class="text-gray-900">{charCount.noSpace}</strong>자</span>
                        <span class="flex items-center gap-1.5"><strong class="text-gray-900">{charCount.bytes}</strong> bytes</span>
                    </div>
                    <button class="text-indigo-600 hover:text-indigo-800 transition-colors flex items-center gap-1" onclick={() => navigator.clipboard.writeText(generatedText)}>
                        복사하기
                    </button>
                </div>
            {:else if isGenerating}
                <div class="h-full flex items-center justify-center text-gray-400 animate-pulse">
                    AI가 열심히 작성중입니다...
                </div>
            {:else}
                <div class="h-full flex items-center justify-center text-gray-400">
                    왼쪽의 정보를 입력하고 생성 버튼을 눌러주세요.
                </div>
            {/if}
        </div>
    </div>
</div>
